services:
  db:
    image: postgres:15-alpine
    container_name: complaintsdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: complaintsdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  seed:
    image: node:20-alpine
    container_name: prisma_seed
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "npm install &&
       npx prisma generate &&
       npx prisma migrate deploy &&
       npx tsx prisma/seed.ts"

volumes:
  db_data: