services:
  db:
    image: postgres:15-alpine
    container_name: complaintsdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: complaintsdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 3

  app:
    build: .
    container_name: customer_management_app
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/complaintsdb"
      PORT: 3001
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db_data: