services:
  db:
    image: postgres:15
    container_name: complaintsdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: complaintsdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: unless-stopped

  app:
    build: .
    container_name: customer_management_app
    command: npm run dev
    ports:
      - "3001:3000" # Changed port mapping from 3000:3000 to 3001:3000
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/complaintsdb"
    depends_on:
      - db
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app

volumes:
  db_data: